/**
 * Showcase data loader — read-from-JSON implementations of the live
 * queries used by the routes shipped in the static export. Activated by
 * `process.env.SHOWCASE === "1"`. Files live in `public/showcase-data/`,
 * generated by `scripts/showcase-snapshot.ts`.
 *
 * Server-only (uses `node:fs`). Imports are top-level on purpose so
 * Next.js detects the read at build-time.
 */

import "server-only"

import * as fs from "node:fs"
import * as path from "node:path"

import type {
  OperatorThread,
  OperatorThreadMessage,
  OperatorThreadSummary,
  OperatorSession,
  OperatorSessionPlan,
} from "./types"
import type {
  ThreadCountSummary,
  OperatorThreadPreview,
} from "./queries"

const DATA_ROOT = path.join(process.cwd(), "public/showcase-data")

export const SHOWCASE_WORKSPACE_ID = "showcase"
export const SHOWCASE_OPERATOR = "David Lin-Clark"

export function isShowcase(): boolean {
  return process.env.SHOWCASE === "1"
}

function readJson<T>(rel: string): T {
  const full = path.join(DATA_ROOT, rel)
  return JSON.parse(fs.readFileSync(full, "utf-8")) as T
}

function readJsonOrNull<T>(rel: string): T | null {
  try {
    return readJson<T>(rel)
  } catch {
    return null
  }
}

// ─── Workspace / counts ─────────────────────────────────────────────────────

export interface ShowcaseManifest {
  workspace: {
    id: string
    name: string
    slug: string
    createdAt: string
  }
  operator: string
  generatedAt: string
  threadCount: number
  messageCount: number
  workSessionCount: number
}

let _manifest: ShowcaseManifest | null = null
function getManifest(): ShowcaseManifest {
  if (!_manifest) _manifest = readJson<ShowcaseManifest>("manifest.json")
  return _manifest
}

export function getShowcaseActiveWorkspace() {
  const m = getManifest()
  return {
    id: m.workspace.id,
    label: m.workspace.name,
    isGlobal: false,
    createdAt: m.workspace.createdAt,
    updatedAt: m.workspace.createdAt,
  }
}

export function listShowcaseWorkspaces() {
  return [getShowcaseActiveWorkspace()]
}

export function getShowcaseThreadCounts(): ThreadCountSummary {
  return readJson<ThreadCountSummary>("counts.json")
}

// ─── Threads ────────────────────────────────────────────────────────────────

let _threads: OperatorThread[] | null = null
export function listShowcaseThreads(): OperatorThread[] {
  if (!_threads) _threads = readJson<OperatorThread[]>("threads.json")
  return _threads
}

export function getShowcaseThreadById(id: string): OperatorThread | null {
  const detail = readJsonOrNull<{ thread: OperatorThread }>(`threads/${id}.json`)
  return detail?.thread ?? null
}

export function getShowcaseThreadMessages(id: string): OperatorThreadMessage[] {
  const detail = readJsonOrNull<{ messages: OperatorThreadMessage[] }>(
    `threads/${id}.json`
  )
  return detail?.messages ?? []
}

export function getShowcaseThreadSummaries(_id: string): OperatorThreadSummary[] {
  return []
}

export function getShowcaseThreadPreviews(
  ids: string[]
): Record<string, OperatorThreadPreview> {
  const all = readJson<Record<string, OperatorThreadPreview>>("previews.json")
  if (ids.length === 0) return all
  const out: Record<string, OperatorThreadPreview> = {}
  for (const id of ids) {
    if (all[id]) out[id] = all[id]
  }
  return out
}

// ─── Sessions / plan ────────────────────────────────────────────────────────

export function listShowcaseWorkSessions(): OperatorSession[] {
  return readJson<OperatorSession[]>("work-sessions.json")
}

export function getShowcaseActivePlan(): OperatorSessionPlan {
  return readJson<OperatorSessionPlan>("plan.json")
}

export function listShowcasePlans(): OperatorSessionPlan[] {
  return readJson<OperatorSessionPlan[]>("plans.json")
}

/**
 * Adapter from the snapshot's `OperatorSessionPlan` (DB-shape) into the
 * `ActivePlan` shape that `PlanAndWork` consumes. Mirrors the work that
 * `activePlanFromPlan()` does in `app/2/v2/data/load.ts`, minus the
 * fulfillment/coverage logic (showcase has no fulfillments).
 */
export function getShowcaseActivePlanAdapted(): {
  id: string
  title: string
  sketchedAtLabel: string
  steps: Array<{
    id: string
    n: number
    title: string
    description: string
    status: "covered" | "in-motion" | "open" | "drifting" | "skipped"
    parentStepId: string | null
    positionX: number | null
    positionY: number | null
    coverImageUrl: string | null
    coverage: { items: number; lastSnippet?: string }
  }>
  goal: string | null
  outcome: string | null
  state: "drafting" | "active" | "paused" | "shipped" | "archived"
  pinned: boolean
  activeSessionId: string | null
  isBlankDraft: boolean
} {
  const plan = getShowcaseActivePlan()
  const sketchedAtLabel = new Date(plan.createdAt).toLocaleTimeString(undefined, {
    hour: "numeric",
    minute: "2-digit",
  })
  return {
    id: plan.id,
    title: plan.title,
    sketchedAtLabel,
    steps: plan.steps.map((s, i) => ({
      id: s.id,
      n: s.order + 1,
      title: s.title,
      description: s.description ?? "",
      status: s.status === "open" ? "open" : s.status,
      parentStepId: s.parentStepId,
      positionX: s.positionX,
      positionY: s.positionY,
      coverImageUrl: s.coverImageUrl,
      coverage: { items: 0 },
    })),
    goal: plan.goal,
    outcome: plan.outcome,
    state: plan.state,
    pinned: plan.pinned,
    activeSessionId: null,
    isBlankDraft: false,
  }
}

// ─── Dashboard stats ─────────────────────────────────────────────────────────

export function getShowcaseDashboardStats() {
  const counts = getShowcaseThreadCounts()
  return {
    totalThreads: counts.total,
    promoted: counts.byState.promoted ?? 0,
    inReview: counts.byState["in-review"] ?? 0,
    imported: counts.byState.imported ?? 0,
    recentImportRuns: 0,
  }
}

// ─── Sessions list extras ───────────────────────────────────────────────────

export function getShowcaseTopThreadsPerSession(): Record<
  string,
  Array<{ threadId: string; title: string | null; messageCount: number }>
> {
  return readJson("top-threads-per-session.json")
}

export function getShowcaseDailyActivity(): Array<{
  date: string
  messageCount: number
}> {
  return readJson("daily-activity.json")
}

// ─── Pulse graph ────────────────────────────────────────────────────────────

/**
 * Pre-built `PulseGraph` for the most-recent work session. Shape
 * matches `app/2/v2/data/load-pulse.ts::PulseGraph` so the live
 * `<PulseView />` renders unchanged. Returns `null` when no session
 * has content — the view handles null with an empty state.
 */
export function getShowcasePulseGraph(): unknown | null {
  return readJsonOrNull("pulse-default.json")
}

// ─── Static params helpers ──────────────────────────────────────────────────

export function listShowcaseThreadIds(): string[] {
  return listShowcaseThreads().map((t) => t.id)
}

export function listShowcaseSessionIds(): string[] {
  return listShowcaseWorkSessions().map((s) => s.id)
}
