"use client"

import * as React from "react"
import { usePathname, useRouter } from "next/navigation"
import { HoverCard as HoverCardPrimitive } from "radix-ui"

const SHOWCASE_MODE = process.env.NEXT_PUBLIC_SHOWCASE === "1"
import {
  Bot,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  History,
  Hourglass,
  Moon,
  MoonStar,
  Sun,
  SunMoon,
  Sunrise,
  Sunset,
  User2,
  type LucideIcon,
} from "lucide-react"

import { cn } from "@/registry/new-york-v4/lib/utils"
import { defaultSessionLabel } from "@/lib/operator-studio/sessions"
import type {
  OperatorSession,
  OperatorThread,
} from "@/lib/operator-studio/types"
import { SourceAppToken } from "./source-apps"
import { useWayseer } from "./wayseer-context"

const STORAGE_KEY_OPEN = "operator_studio_recent_rail_open"
const STORAGE_KEY_MODE = "operator_studio_recent_rail_mode"

type RailMode = "threads" | "messages"

type ThreadGroup = {
  session: OperatorSession
  threads: OperatorThread[]
}

type ExchangePart = {
  id: string
  content: string
  createdAt: string
}

type RecentExchange = {
  id: string
  threadId: string
  threadTitle: string
  threadSourceApp: string
  user: ExchangePart | null
  assistant: ExchangePart | null
  lastActivityAt: string
}

type ExchangeGroup = {
  session: OperatorSession
  exchanges: RecentExchange[]
}

/**
 * Secondary sidebar mounted next to the main `<Sidebar>`. Has two
 * modes: "threads" (default — recent threads grouped by session) and
 * "messages" (recent message snippets with thread context). Both
 * group by session so the temporal scaffold matches across modes.
 *
 * Open/closed and mode preferences persist in localStorage so a user
 * who lives in "messages" mode doesn't get bumped back to "threads"
 * on every nav.
 */
export function RecentChatsRail({ workspaceId }: { workspaceId: string }) {
  const router = useRouter()
  const pathname = usePathname()
  const { enabled: wayseerEnabled } = useWayseer()
  const [open, setOpen] = React.useState<boolean | null>(null)
  const [mode, setMode] = React.useState<RailMode>("threads")
  const [threadGroups, setThreadGroups] = React.useState<
    ThreadGroup[] | null
  >(null)
  const [exchangeGroups, setExchangeGroups] = React.useState<
    ExchangeGroup[] | null
  >(null)
  const [error, setError] = React.useState<string | null>(null)
  const [wayseerSnippets, setWayseerSnippets] = React.useState<
    Record<string, string>
  >({})
  // Set of thread ids whose operator typed the configured done
  // sentinel as a user turn. Source of truth lives in the API
  // response; the rail dims matching rows the same way the Work tab
  // does, so the "completed" signal is consistent across surfaces.
  const [doneThreadIds, setDoneThreadIds] = React.useState<Set<string>>(
    () => new Set()
  )

  // Hydrate persisted prefs once on mount.
  React.useEffect(() => {
    const storedOpen = window.localStorage.getItem(STORAGE_KEY_OPEN)
    setOpen(storedOpen === null ? true : storedOpen === "1")
    const storedMode = window.localStorage.getItem(STORAGE_KEY_MODE)
    if (storedMode === "messages" || storedMode === "threads") {
      setMode(storedMode)
    }
  }, [])

  React.useEffect(() => {
    if (open === null) return
    window.localStorage.setItem(STORAGE_KEY_OPEN, open ? "1" : "0")
  }, [open])

  React.useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY_MODE, mode)
  }, [mode])

  // Refetch when workspace or mode changes. Each mode owns its own
  // cache so flipping back to a previously-loaded mode is instant.
  React.useEffect(() => {
    let cancelled = false
    setError(null)
    // In showcase mode the rail reads from a static JSON snapshot
    // (no API runtime). The JSON files are generated by
    // `scripts/showcase-snapshot.ts` and shipped to `public/showcase-data/`.
    const url = SHOWCASE_MODE
      ? mode === "messages"
        ? "/showcase-data/recent-with-exchanges.json"
        : "/showcase-data/recent-with-threads.json"
      : mode === "messages"
        ? "/api/operator-studio/sessions/recent-with-threads?mode=messages&limit=8"
        : "/api/operator-studio/sessions/recent-with-threads?limit=8"
    if (mode === "messages") setExchangeGroups(null)
    else setThreadGroups(null)

    fetch(url)
      .then((r) => (r.ok ? r.json() : Promise.reject(r.statusText)))
      .then((data) => {
        if (cancelled) return
        if (mode === "messages") setExchangeGroups(data.groups ?? [])
        else setThreadGroups(data.groups ?? [])
        setDoneThreadIds(
          new Set<string>(
            Array.isArray(data.doneThreadIds) ? data.doneThreadIds : []
          )
        )
      })
      .catch((err) => {
        if (cancelled) return
        setError(typeof err === "string" ? err : "Failed to load")
      })
    return () => {
      cancelled = true
    }
  }, [workspaceId, mode])

  // Batch-fetch Wayseer enrichment snippets for the threads currently
  // shown in the rail. Only when Wayseer is enabled — when off, the
  // snippet line is hidden entirely. Refetches whenever the visible
  // thread set changes.
  React.useEffect(() => {
    // No wayseer enrichments in the static showcase — endpoint
    // doesn't exist and the snippets are LLM-generated, not part of
    // the snapshot.
    if (SHOWCASE_MODE || !wayseerEnabled) {
      setWayseerSnippets({})
      return
    }
    if (mode !== "threads" || !threadGroups) return
    const ids = threadGroups
      .flatMap((g) => g.threads.map((t) => t.id))
      .slice(0, 50)
    if (ids.length === 0) {
      setWayseerSnippets({})
      return
    }
    let cancelled = false
    fetch(
      `/api/operator-studio/wayseer/enrichments?threadIds=${ids
        .map(encodeURIComponent)
        .join(",")}`
    )
      .then((r) => (r.ok ? r.json() : Promise.reject(r.statusText)))
      .then((data) => {
        if (cancelled) return
        setWayseerSnippets(
          (data?.snippets as Record<string, string> | undefined) ?? {}
        )
      })
      .catch(() => {
        if (!cancelled) setWayseerSnippets({})
      })
    return () => {
      cancelled = true
    }
  }, [wayseerEnabled, mode, threadGroups])

  // Pre-warm the hover-preview cache for every thread visible in the
  // rail so first hover is instant. Bulk endpoint returns just bookend
  // messages (first/last user + assistant) — cheap even for huge threads.
  React.useEffect(() => {
    if (mode !== "threads" || !threadGroups) return
    const ids = threadGroups
      .flatMap((g) => g.threads.map((t) => t.id))
      .filter((id) => !previewCache.has(id))
    if (ids.length === 0) return
    primeThreadPreviews(ids)
  }, [mode, threadGroups])

  if (open === null) return null

  if (!open) {
    return (
      <aside
        aria-label="Recent chats (collapsed)"
        className="hidden md:flex h-svh w-8 shrink-0 flex-col items-center border-r bg-sidebar/60 py-2"
      >
        <button
          type="button"
          onClick={() => setOpen(true)}
          aria-label="Show recent chats"
          title="Show recent chats"
          className="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
        >
          <History className="size-4" />
        </button>
        <button
          type="button"
          onClick={() => setOpen(true)}
          aria-label="Expand recent chats"
          className="mt-1 flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
        >
          <ChevronRight className="size-3.5" />
        </button>
      </aside>
    )
  }

  return (
    <aside
      aria-label="Recent chats"
      className="hidden md:flex h-svh w-64 shrink-0 flex-col border-r bg-sidebar/60"
    >
      <div className="flex h-10 shrink-0 items-center gap-2 border-b px-3">
        <History className="size-3.5 text-muted-foreground" />
        <span className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">
          Recent
        </span>
        <button
          type="button"
          onClick={() => setOpen(false)}
          aria-label="Hide recent chats"
          title="Hide recent chats"
          className="ml-auto flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground"
        >
          <ChevronLeft className="size-3.5" />
        </button>
      </div>
      <ModeTabs mode={mode} onChange={setMode} />
      <div className="min-h-0 flex-1 overflow-y-auto px-1.5 py-2">
        {error && (
          <p className="px-2 py-3 text-xs text-muted-foreground italic">
            Couldn’t load recent activity.
          </p>
        )}
        {!error && mode === "threads" && (
          <ThreadsView
            groups={threadGroups}
            activePath={pathname}
            onNavigate={(href) => router.push(href)}
            wayseerSnippets={wayseerSnippets}
            doneThreadIds={doneThreadIds}
          />
        )}
        {!error && mode === "messages" && (
          <ExchangesView
            groups={exchangeGroups}
            activePath={pathname}
            onNavigate={(href) => router.push(href)}
            doneThreadIds={doneThreadIds}
          />
        )}
      </div>
    </aside>
  )
}

// ─── Tabs ────────────────────────────────────────────────────────────────────

function ModeTabs({
  mode,
  onChange,
}: {
  mode: RailMode
  onChange: (next: RailMode) => void
}) {
  return (
    <div
      role="tablist"
      aria-label="Recent activity view"
      className="flex shrink-0 gap-1 border-b px-2 py-1.5"
    >
      <TabButton
        active={mode === "threads"}
        onClick={() => onChange("threads")}
        label="Threads"
      />
      <TabButton
        active={mode === "messages"}
        onClick={() => onChange("messages")}
        label="Messages"
      />
    </div>
  )
}

function TabButton({
  active,
  onClick,
  label,
}: {
  active: boolean
  onClick: () => void
  label: string
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      className={cn(
        "flex-1 rounded px-2 py-1 text-[11px] font-medium uppercase tracking-wider transition-colors",
        active
          ? "bg-sidebar-accent text-sidebar-accent-foreground"
          : "text-muted-foreground hover:bg-sidebar-accent/40 hover:text-foreground"
      )}
    >
      {label}
    </button>
  )
}

// ─── Threads view ────────────────────────────────────────────────────────────

function ThreadsView({
  groups,
  activePath,
  onNavigate,
  wayseerSnippets,
  doneThreadIds,
}: {
  groups: ThreadGroup[] | null
  activePath: string
  onNavigate: (href: string) => void
  wayseerSnippets: Record<string, string>
  doneThreadIds: Set<string>
}) {
  if (groups === null) {
    return (
      <p className="px-2 py-3 text-xs text-muted-foreground italic">Loading…</p>
    )
  }
  if (groups.length === 0) {
    return (
      <p className="px-2 py-3 text-xs text-muted-foreground italic">
        No sessions yet.
      </p>
    )
  }
  return (
    <>
      {groups.map(({ session, threads }) => (
        <div key={session.id} className="mb-3">
          <SessionHeader
            session={session}
            count={threads.length}
            activePath={activePath}
            onNavigate={onNavigate}
          />
          {threads.length === 0 ? (
            <p className="px-2 py-1 text-[11px] italic text-muted-foreground/70">
              No threads.
            </p>
          ) : (
            <ul className="mt-0.5">
              {[...threads]
                .sort(
                  (a, b) =>
                    new Date(b.updatedAt).getTime() -
                    new Date(a.updatedAt).getTime()
                )
                .map((t) => {
                  const title =
                    t.promotedTitle ?? t.rawTitle ?? "Untitled thread"
                  const href = `/operator-studio/threads/${t.id}`
                  const isActive = activePath === href
                  const snippet = wayseerSnippets[t.id]
                  const isDone = doneThreadIds.has(t.id)
                  return (
                    <li key={t.id}>
                      <ThreadHoverPreview
                        threadId={t.id}
                        title={title}
                        sourceApp={t.sourceApp}
                      >
                        <button
                          type="button"
                          onClick={() => onNavigate(href)}
                          className={cn(
                            "flex w-full flex-col gap-0.5 rounded px-2 py-1 text-left text-[12px]",
                            isActive
                              ? "bg-sidebar-accent text-sidebar-accent-foreground"
                              : isDone
                                ? "bg-emerald-50/70 dark:bg-emerald-950/40 opacity-70 hover:opacity-90 hover:bg-emerald-100/70 dark:hover:bg-emerald-950/60"
                                : "text-foreground/80 hover:bg-sidebar-accent/50 hover:text-foreground"
                          )}
                        >
                          <span className="flex w-full items-center gap-1.5">
                            <SourceAppToken
                              source={t.sourceApp}
                              variant="plain"
                              size="sm"
                              showLabel={false}
                              className="shrink-0"
                            />
                            <span className="min-w-0 flex-1 truncate">
                              {title}
                            </span>
                            {isDone && (
                              <CheckCircle2
                                className="h-3 w-3 shrink-0 text-emerald-500 dark:text-emerald-400"
                                aria-label="Marked done"
                              />
                            )}
                            <span className="shrink-0 tabular-nums text-[10px] text-muted-foreground/70">
                              {relativeTime(t.updatedAt)}
                            </span>
                          </span>
                          {snippet && (
                            <span className="ml-[1.4rem] truncate text-[10.5px] leading-snug text-muted-foreground/80">
                              {snippet}
                            </span>
                          )}
                        </button>
                      </ThreadHoverPreview>
                    </li>
                  )
                })}
            </ul>
          )}
        </div>
      ))}
    </>
  )
}

// ─── Exchanges view ──────────────────────────────────────────────────────────

function ExchangesView({
  groups,
  activePath,
  onNavigate,
  doneThreadIds,
}: {
  groups: ExchangeGroup[] | null
  activePath: string
  onNavigate: (href: string) => void
  doneThreadIds: Set<string>
}) {
  if (groups === null) {
    return (
      <p className="px-2 py-3 text-xs text-muted-foreground italic">Loading…</p>
    )
  }
  const nonEmpty = groups.filter((g) => g.exchanges.length > 0)
  if (nonEmpty.length === 0) {
    return (
      <p className="px-2 py-3 text-xs text-muted-foreground italic">
        No exchanges yet.
      </p>
    )
  }
  return (
    <>
      {nonEmpty.map(({ session, exchanges }) => (
        <div key={session.id} className="mb-3">
          <SessionHeader
            session={session}
            count={exchanges.length}
            activePath={activePath}
            onNavigate={onNavigate}
          />
          <ul className="mt-1 space-y-1.5">
            {exchanges.map((ex) => (
              <ExchangeCard
                key={ex.id}
                exchange={ex}
                activePath={activePath}
                onNavigate={onNavigate}
                isDone={doneThreadIds.has(ex.threadId)}
              />
            ))}
          </ul>
        </div>
      ))}
    </>
  )
}

/**
 * One exchange = a user prompt + the assistant response, rendered as
 * a single capsule. Each side gets a tight 2-line preview (~120 chars
 * worth) so the back-and-forth is legible at a glance without
 * blowing out the 16rem rail.
 *
 * Click the whole card → jump to the thread. The footer line carries
 * thread title / time / source so the card stays self-contained.
 */
function ExchangeCard({
  exchange,
  activePath,
  onNavigate,
  isDone,
}: {
  exchange: RecentExchange
  activePath: string
  onNavigate: (href: string) => void
  isDone: boolean
}) {
  const href = `/operator-studio/threads/${exchange.threadId}`
  const isActive = activePath === href
  const userSnippet = exchange.user ? trimSnippet(exchange.user.content) : null
  const assistantSnippet = exchange.assistant
    ? trimSnippet(exchange.assistant.content)
    : null
  const tooltip = [
    userSnippet ? `You: ${userSnippet}` : null,
    assistantSnippet ? `AI: ${assistantSnippet}` : null,
    `— ${exchange.threadTitle} · ${formatAbsolute(exchange.lastActivityAt)}`,
  ]
    .filter(Boolean)
    .join("\n\n")

  return (
    <li>
      <button
        type="button"
        onClick={() => onNavigate(href)}
        title={tooltip}
        className={cn(
          "flex w-full flex-col gap-1 rounded-md border px-2 py-1.5 text-left transition-colors",
          isActive
            ? "border-sidebar-accent bg-sidebar-accent text-sidebar-accent-foreground"
            : isDone
              ? "border-emerald-200/60 bg-emerald-50/70 dark:border-emerald-900/40 dark:bg-emerald-950/40 opacity-70 hover:opacity-90"
              : "border-border/40 bg-background/40 hover:border-border hover:bg-sidebar-accent/40"
        )}
      >
        {userSnippet && (
          <ExchangeLine
            role="user"
            content={userSnippet}
            isActive={isActive}
          />
        )}
        {userSnippet && assistantSnippet && (
          <div className="h-px bg-border/40" aria-hidden />
        )}
        {assistantSnippet && (
          <ExchangeLine
            role="assistant"
            content={assistantSnippet}
            isActive={isActive}
          />
        )}
        <div className="flex w-full items-center gap-1.5 pt-0.5">
          <span className="min-w-0 flex-1 truncate text-[10px] text-muted-foreground/80">
            {exchange.threadTitle}
          </span>
          <span className="shrink-0 tabular-nums text-[10px] text-muted-foreground/60">
            {relativeTime(exchange.lastActivityAt)}
          </span>
          <SourceAppToken
            source={exchange.threadSourceApp}
            variant="plain"
            size="sm"
            showLabel={false}
            className="shrink-0"
          />
        </div>
      </button>
    </li>
  )
}

function ExchangeLine({
  role,
  content,
  isActive,
}: {
  role: "user" | "assistant"
  content: string
  isActive: boolean
}) {
  const isUser = role === "user"
  const Icon = isUser ? User2 : Bot
  return (
    <div className="flex w-full items-start gap-1.5">
      <Icon
        className={cn(
          "mt-0.5 size-3 shrink-0",
          isUser
            ? "text-sky-600 dark:text-sky-400"
            : "text-amber-600 dark:text-amber-400"
        )}
      />
      <span
        className={cn(
          "line-clamp-2 min-w-0 flex-1 text-[12px] leading-snug",
          isActive ? "text-sidebar-accent-foreground" : "text-foreground/85"
        )}
      >
        {content}
      </span>
    </div>
  )
}

// ─── Session header ──────────────────────────────────────────────────────────

type TimeBucket =
  | "overnight"
  | "morning"
  | "afternoon"
  | "evening"
  | "late-night"
  | "all-day"

/**
 * Re-derive the session's time-of-day bucket from its actual span so
 * the icon/colour are reliable even when a session has a custom
 * `label`. Mirrors the bucketing rules in `defaultSessionLabel` —
 * keep them in sync.
 */
function sessionBucket(startedAt: string, endedAt: string): TimeBucket {
  const start = new Date(startedAt)
  const end = new Date(endedAt)
  const durationHours =
    (end.getTime() - start.getTime()) / 3_600_000
  if (durationHours >= 10) return "all-day"
  const h = start.getHours()
  if (h < 5) return "overnight"
  if (h < 12) return "morning"
  if (h < 17) return "afternoon"
  if (h < 21) return "evening"
  return "late-night"
}

const BUCKET_META: Record<
  TimeBucket,
  { Icon: LucideIcon; color: string; label: string }
> = {
  overnight: {
    Icon: Moon,
    color: "text-indigo-600/80 dark:text-indigo-400/80",
    label: "overnight",
  },
  morning: {
    Icon: Sunrise,
    color: "text-amber-600/80 dark:text-amber-400/80",
    label: "morning",
  },
  afternoon: {
    Icon: Sun,
    color: "text-yellow-600/80 dark:text-yellow-400/80",
    label: "afternoon",
  },
  evening: {
    Icon: Sunset,
    color: "text-orange-600/80 dark:text-orange-400/80",
    label: "evening",
  },
  "late-night": {
    Icon: MoonStar,
    color: "text-violet-600/80 dark:text-violet-400/80",
    label: "late night",
  },
  "all-day": {
    Icon: SunMoon,
    color: "text-sky-600/80 dark:text-sky-400/80",
    label: "all day",
  },
}

function SessionHeader({
  session,
  count,
  activePath,
  onNavigate,
}: {
  session: OperatorSession
  count: number
  activePath: string
  onNavigate: (href: string) => void
}) {
  const fallbackLabel = defaultSessionLabel(
    new Date(session.startedAt),
    new Date(session.endedAt)
  )
  const customLabel = session.label
  const day = new Date(session.startedAt).toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
  })
  const bucket = sessionBucket(session.startedAt, session.endedAt)
  const meta = BUCKET_META[bucket]
  const href = `/operator-studio/sessions/${session.id}`
  const active = activePath === href
  const range = formatSessionRange(session.startedAt, session.endedAt)
  const duration = formatSessionDuration(session.startedAt, session.endedAt)
  return (
    <button
      type="button"
      onClick={() => onNavigate(href)}
      className={cn(
        "group flex w-full flex-col gap-0 rounded px-2 py-1 text-left",
        active
          ? "bg-sidebar-accent text-sidebar-accent-foreground"
          : "hover:bg-sidebar-accent/40"
      )}
      title={`${customLabel ?? fallbackLabel}\n${range} · ${duration}`}
    >
      <div className="flex w-full items-center gap-1.5">
        <meta.Icon
          aria-hidden
          className={cn(
            "size-3.5 shrink-0 transition-transform group-hover:scale-110",
            meta.color
          )}
        />
        <span
          className={cn(
            "flex min-w-0 flex-1 items-baseline gap-1.5 truncate text-[11px] font-medium uppercase tracking-wider",
            active ? "text-sidebar-accent-foreground" : "text-foreground/80"
          )}
        >
          {customLabel ? (
            <span className="truncate">{customLabel}</span>
          ) : (
            <>
              <span className="truncate">{day}</span>
              <span className="text-muted-foreground/40" aria-hidden>
                ·
              </span>
              <span className="truncate text-muted-foreground">{meta.label}</span>
            </>
          )}
        </span>
        <span className="shrink-0 tabular-nums text-[10px] text-muted-foreground/70">
          {count}
        </span>
      </div>
      <div className="flex w-full items-center gap-1.5 pl-[20px] text-[10px] text-muted-foreground/70">
        <span className="tabular-nums">{range}</span>
        <span aria-hidden>·</span>
        <span className="tabular-nums">{duration}</span>
      </div>
    </button>
  )
}

// ─── Time formatting ─────────────────────────────────────────────────────────

function relativeTime(iso: string): string {
  const now = Date.now()
  const then = new Date(iso).getTime()
  const diff = now - then
  if (diff < 0) return "just now"
  const mins = Math.floor(diff / 60_000)
  if (mins < 1) return "just now"
  if (mins < 60) return `${mins}m`
  const hours = Math.floor(mins / 60)
  if (hours < 24) return `${hours}h`
  const days = Math.floor(hours / 24)
  if (days < 7) return `${days}d`
  if (days < 30) return `${Math.floor(days / 7)}w`
  return new Date(iso).toLocaleDateString(undefined, {
    month: "short",
    day: "numeric",
  })
}

function formatAbsolute(iso: string): string {
  return new Date(iso).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  })
}

/** "9:14a → 11:35a" — compact lowercase am/pm to keep the rail tight. */
function formatSessionRange(startedAt: string, endedAt: string): string {
  return `${formatClock(startedAt)} → ${formatClock(endedAt)}`
}

function formatClock(iso: string): string {
  const d = new Date(iso)
  const h24 = d.getHours()
  const m = d.getMinutes()
  const am = h24 < 12
  const h12 = h24 % 12 === 0 ? 12 : h24 % 12
  const mm = m === 0 ? "" : `:${m.toString().padStart(2, "0")}`
  return `${h12}${mm}${am ? "a" : "p"}`
}

function formatSessionDuration(startedAt: string, endedAt: string): string {
  const ms = new Date(endedAt).getTime() - new Date(startedAt).getTime()
  if (ms <= 0) return "—"
  const mins = Math.round(ms / 60_000)
  if (mins < 60) return `${mins}m`
  const hours = Math.floor(mins / 60)
  const rem = mins % 60
  return rem === 0 ? `${hours}h` : `${hours}h ${rem}m`
}

function trimSnippet(content: string): string {
  const collapsed = content.replace(/\s+/g, " ").trim()
  if (collapsed.length <= 140) return collapsed
  return collapsed.slice(0, 137) + "…"
}

// ─── Thread hover preview ────────────────────────────────────────────────────

type ThreadPreviewMessage = {
  role: "user" | "assistant"
  content: string
  createdAt: string
}

type ThreadPreview = {
  startedAt: string
  endedAt: string
  messageCount: number
  firstUser: ThreadPreviewMessage | null
  firstAssistant: ThreadPreviewMessage | null
  lastUser: ThreadPreviewMessage | null
  lastAssistant: ThreadPreviewMessage | null
  middleCount: number
}

const previewCache = new Map<string, ThreadPreview>()
const previewInflight = new Map<string, Promise<ThreadPreview | null>>()

type BookendDto = {
  role: "user" | "assistant"
  content: string
  createdAt: string
}
type PreviewDto = {
  threadId: string
  startedAt: string
  endedAt: string
  messageCount: number
  firstUser: BookendDto | null
  firstAssistant: BookendDto | null
  lastUser: BookendDto | null
  lastAssistant: BookendDto | null
}

function previewFromDto(dto: PreviewDto): ThreadPreview {
  const anchors: BookendDto[] = [
    dto.firstUser,
    dto.firstAssistant,
    dto.lastUser,
    dto.lastAssistant,
  ].filter((b): b is BookendDto => b !== null)
  const innerCount = Math.max(0, dto.messageCount - anchors.length)
  return {
    startedAt: dto.startedAt,
    endedAt: dto.endedAt,
    messageCount: dto.messageCount,
    firstUser: dto.firstUser,
    firstAssistant: dto.firstAssistant,
    lastUser: dto.lastUser,
    lastAssistant: dto.lastAssistant,
    middleCount: innerCount,
  }
}

/**
 * Bulk pre-warm: hits the previews endpoint for many threads at once.
 * Splits into chunks so URL length stays sane. Each chunk's promise is
 * also registered in `previewInflight` for every id in that chunk —
 * that way a hover that fires *during* the prewarm window can `await`
 * the same in-flight request instead of issuing a duplicate fetch and
 * flashing a "Loading…" state.
 */
function primeThreadPreviews(threadIds: string[]): Promise<void> {
  const todo = threadIds.filter(
    (id) => !previewCache.has(id) && !previewInflight.has(id)
  )
  if (todo.length === 0) return Promise.resolve()
  const chunks: string[][] = []
  const chunkSize = 50
  for (let i = 0; i < todo.length; i += chunkSize) {
    chunks.push(todo.slice(i, i + chunkSize))
  }
  const chunkPromises = chunks.map((ids) => {
    const p = (async () => {
      try {
        // Showcase mode reads the entire previews map up-front from a
        // static JSON file; the API endpoint doesn't exist in the
        // static export. We fetch the whole map (it's small —
        // bookend messages, not full transcripts) and pluck the ids.
        const r = await fetch(
          SHOWCASE_MODE
            ? "/showcase-data/previews.json"
            : `/api/operator-studio/threads/previews?ids=${ids
                .map(encodeURIComponent)
                .join(",")}`
        )
        if (!r.ok) return
        const raw = await r.json()
        // Showcase JSON is the previews map directly; the live API
        // wraps it in `{ previews: { … } }`.
        const map: Record<string, PreviewDto> = SHOWCASE_MODE
          ? raw
          : raw?.previews ?? {}
        for (const id of ids) {
          const dto = map[id]
          if (!dto) continue
          // Title is held in the DOM trigger; the popover passes its own
          // fallbackTitle. Cache only what the bulk endpoint provides.
          previewCache.set(id, previewFromDto(dto))
        }
      } catch {
        // Best-effort prewarm; per-item fetch will retry on next hover.
      }
    })()
    // Register the SAME promise for every id in this chunk so concurrent
    // per-thread hovers attach to it instead of firing their own fetch.
    const sharedPromise = p.then(() => previewCache.get(ids[0]) ?? null)
    for (const id of ids) {
      previewInflight.set(id, p.then(() => previewCache.get(id) ?? null))
    }
    p.finally(() => {
      for (const id of ids) previewInflight.delete(id)
    })
    return sharedPromise
  })
  return Promise.all(chunkPromises).then(() => undefined)
}

/**
 * Per-thread fallback fetcher (only used if prewarm hasn't populated
 * the cache yet — e.g. a thread renders mid-flight). Goes through the
 * same bulk endpoint so the response shape stays uniform.
 */
function fetchThreadPreview(threadId: string): Promise<ThreadPreview | null> {
  const cached = previewCache.get(threadId)
  if (cached) return Promise.resolve(cached)
  const inflight = previewInflight.get(threadId)
  if (inflight) return inflight
  // Not in flight — issue a single-thread fetch via the bulk path.
  primeThreadPreviews([threadId])
  return previewInflight.get(threadId) ?? Promise.resolve(null)
}

function ThreadHoverPreview({
  threadId,
  title,
  sourceApp,
  children,
}: {
  threadId: string
  title: string
  sourceApp: string
  children: React.ReactNode
}) {
  const [open, setOpen] = React.useState(false)
  const [preview, setPreview] = React.useState<ThreadPreview | null>(
    () => previewCache.get(threadId) ?? null
  )
  const [loading, setLoading] = React.useState(false)

  React.useEffect(() => {
    if (!open || preview) return
    let cancelled = false
    setLoading(true)
    fetchThreadPreview(threadId).then((p) => {
      if (cancelled) return
      setPreview(p)
      setLoading(false)
    })
    return () => {
      cancelled = true
    }
  }, [open, preview, threadId])

  return (
    <HoverCardPrimitive.Root
      openDelay={0}
      closeDelay={0}
      open={open}
      onOpenChange={setOpen}
    >
      <HoverCardPrimitive.Trigger asChild>
        {children}
      </HoverCardPrimitive.Trigger>
      <HoverCardPrimitive.Portal>
        <HoverCardPrimitive.Content
          side="right"
          align="start"
          sideOffset={8}
          collisionPadding={12}
          className={cn(
            "z-50 w-[22rem] max-w-[90vw] rounded-md border bg-popover p-3 text-popover-foreground shadow-lg outline-none"
          )}
        >
          <ThreadPreviewBody
            fallbackTitle={title}
            sourceApp={sourceApp}
            preview={preview}
            loading={loading}
          />
        </HoverCardPrimitive.Content>
      </HoverCardPrimitive.Portal>
    </HoverCardPrimitive.Root>
  )
}

function ThreadPreviewBody({
  fallbackTitle,
  sourceApp,
  preview,
  loading,
}: {
  fallbackTitle: string
  sourceApp: string
  preview: ThreadPreview | null
  loading: boolean
}) {
  if (!preview) {
    return (
      <div className="space-y-2">
        <PreviewHeader title={fallbackTitle} sourceApp={sourceApp} />
        <p className="text-[11px] italic text-muted-foreground">
          {loading ? "Loading preview…" : "No preview available."}
        </p>
      </div>
    )
  }
  const showLast = preview.lastUser || preview.lastAssistant
  return (
    <div className="space-y-2.5">
      <PreviewHeader
        title={fallbackTitle}
        sourceApp={sourceApp}
        startedAt={preview.startedAt}
        endedAt={preview.endedAt}
        messageCount={preview.messageCount}
      />
      <div className="space-y-1.5">
        {preview.firstUser && (
          <PreviewMessage
            role="user"
            content={preview.firstUser.content}
            timestamp={preview.firstUser.createdAt}
          />
        )}
        {preview.firstAssistant && (
          <PreviewMessage
            role="assistant"
            content={preview.firstAssistant.content}
            timestamp={preview.firstAssistant.createdAt}
          />
        )}
      </div>
      {showLast && (
        <ReceiptRip
          fromIso={
            (preview.firstAssistant ?? preview.firstUser)?.createdAt ??
            preview.startedAt
          }
          toIso={
            (preview.lastUser ?? preview.lastAssistant)?.createdAt ??
            preview.endedAt
          }
          middleCount={preview.middleCount}
        />
      )}
      {showLast && (
        <div className="space-y-1.5">
          {preview.lastUser && (
            <PreviewMessage
              role="user"
              content={preview.lastUser.content}
              timestamp={preview.lastUser.createdAt}
            />
          )}
          {preview.lastAssistant && (
            <PreviewMessage
              role="assistant"
              content={preview.lastAssistant.content}
              timestamp={preview.lastAssistant.createdAt}
            />
          )}
        </div>
      )}
    </div>
  )
}

function PreviewHeader({
  title,
  sourceApp,
  startedAt,
  endedAt,
  messageCount,
}: {
  title: string
  sourceApp: string
  startedAt?: string
  endedAt?: string
  messageCount?: number
}) {
  return (
    <div className="space-y-1 border-b border-border/50 pb-2">
      <div className="flex items-start gap-2">
        <SourceAppToken
          source={sourceApp}
          variant="plain"
          size="sm"
          showLabel={false}
          className="mt-0.5 shrink-0"
        />
        <h3 className="text-[13px] font-medium leading-snug text-foreground">
          {title}
        </h3>
      </div>
      {startedAt && (
        <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground/80">
          <span className="tabular-nums">{formatAbsolute(startedAt)}</span>
          {endedAt && endedAt !== startedAt && (
            <>
              <span aria-hidden>→</span>
              <span className="tabular-nums">{formatAbsolute(endedAt)}</span>
            </>
          )}
          {typeof messageCount === "number" && messageCount > 0 && (
            <>
              <span aria-hidden>·</span>
              <span className="tabular-nums">
                {messageCount} {messageCount === 1 ? "message" : "messages"}
              </span>
            </>
          )}
        </div>
      )}
    </div>
  )
}

function PreviewMessage({
  role,
  content,
  timestamp,
}: {
  role: "user" | "assistant"
  content: string
  timestamp: string
}) {
  const isUser = role === "user"
  const Icon = isUser ? User2 : Bot
  return (
    <div className="flex items-start gap-2">
      <Icon
        aria-hidden
        className={cn(
          "mt-0.5 size-3 shrink-0",
          isUser
            ? "text-sky-600 dark:text-sky-400"
            : "text-amber-600 dark:text-amber-400"
        )}
      />
      <div className="min-w-0 flex-1">
        <div className="flex items-baseline justify-between gap-2">
          <span
            className={cn(
              "text-[10px] font-medium uppercase tracking-wider",
              isUser
                ? "text-sky-700 dark:text-sky-300"
                : "text-amber-700 dark:text-amber-300"
            )}
          >
            {isUser ? "You" : "AI"}
          </span>
          <time
            dateTime={timestamp}
            className="shrink-0 tabular-nums text-[9.5px] text-muted-foreground/70"
          >
            {formatAbsolute(timestamp)}
          </time>
        </div>
        <p className="line-clamp-3 text-[11.5px] leading-snug text-foreground/85">
          {trimSnippet(content)}
        </p>
      </div>
    </div>
  )
}

/**
 * Receipt-rip divider: a perforated line with the elapsed time and
 * a count of hidden messages in the middle. Visually evokes
 * "...time passes..." between the opening and closing exchanges.
 */
function ReceiptRip({
  fromIso,
  toIso,
  middleCount,
}: {
  fromIso: string
  toIso: string
  middleCount: number
}) {
  const gap = formatGap(fromIso, toIso)
  const hidden =
    middleCount > 0
      ? `${middleCount} ${middleCount === 1 ? "message" : "messages"} hidden`
      : null
  return (
    <div
      aria-hidden
      className="flex items-center gap-2 px-0.5 text-muted-foreground/70"
    >
      <Perforation />
      <div className="flex shrink-0 items-center gap-1 text-[9.5px] uppercase tracking-wider">
        <Hourglass className="size-2.5" />
        <span className="tabular-nums">{gap}</span>
        {hidden && (
          <>
            <span aria-hidden>·</span>
            <span className="tabular-nums">{hidden}</span>
          </>
        )}
      </div>
      <Perforation />
    </div>
  )
}

function Perforation() {
  return (
    <div
      className="h-px flex-1"
      style={{
        backgroundImage:
          "repeating-linear-gradient(to right, currentColor 0 3px, transparent 3px 7px)",
      }}
    />
  )
}

function formatGap(fromIso: string, toIso: string): string {
  const ms = new Date(toIso).getTime() - new Date(fromIso).getTime()
  if (!Number.isFinite(ms) || ms <= 0) return "—"
  const sec = Math.round(ms / 1000)
  if (sec < 60) return `${sec}s`
  const mins = Math.round(sec / 60)
  if (mins < 60) return `${mins}m`
  const hours = Math.floor(mins / 60)
  const remMin = mins % 60
  if (hours < 24) return remMin === 0 ? `${hours}h` : `${hours}h ${remMin}m`
  const days = Math.floor(hours / 24)
  const remHrs = hours % 24
  return remHrs === 0 ? `${days}d` : `${days}d ${remHrs}h`
}
